# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'zhuanshi' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'YYKit'
  pod 'SDCycleScrollView'

  target 'zhuanshiTests' do
    inherit! :search_paths
    # Pods for testing    
  end

  target 'zhuanshiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
